name: Lint and Test Charts

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  HELM_VERSION: 3.4.0
  PYTHON_VERSION: 3.7

jobs:
  lint-chart:
    name: Lint chart
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v1
        with:
          version: "${{ env.HELM_VERSION }}"

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "${{ env.PYTHON_VERSION }}"

      - name: Run Helm lint
        run: helm lint charts/*

      - name: Run Chart Testing lint
        uses: helm/chart-testing-action@v1.1.0
        with:
          command: lint
          config: .github/config/chart-testing.yaml

  test-install-chart:
    name: Test chart installation on K8s
    runs-on: ubuntu-latest
    needs:
      - lint-chart
    strategy:
      matrix:
        k8s:
          - v1.18.19
          - v1.19.11
          - v1.20.7
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v1
        with:
          version: "${{ env.HELM_VERSION }}"

      - uses: actions/setup-python@v2
        with:
          python-version: "${{ env.PYTHON_VERSION }}"

      - name: Create kind ${{ matrix.k8s }} cluster
        uses: helm/kind-action@v1.2.0
        with:
          node_image: kindest/node:${{ matrix.k8s }}

      - name: Check K8s nodes
        run: |
          kubectl get nodes;

      - name: Run Chart Testing install
        uses: helm/chart-testing-action@v1.1.0
        with:
          command: install
          config: .github/config/chart-testing.yaml
